forms/create.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired

class CreateForm(FlaskForm):
    id = IntegerField("Id: ", validators=[DataRequired()])
    content = StringField("Content: ", validators=[DataRequired()])

app.py
from flask import Flask
from blueprints.agenda import agenda

app = Flask(__name__)
app.secret_key = "qwerty12345"

app.register_blueprint(agenda, url_prefix='/agenda/api')

blueprints/agenda.py
import json

from flask import Blueprint, url_for, redirect, render_template
from forms.create import CreateForm

dataAgenda = json.loads(
	json.dumps([
		{
			'id': 1,
			'content': 'Cita Ortodoncia'
		},
		{
			'id': 2,
			'content': 'Cita Odontologia'
		},
		{
			'id': 3,
			'content': 'Cita Empresa'
		}
	])
)

agenda = Blueprint('agenda', __name__, template_folder='templates', static_folder='static')

@agenda.route('/', methods = [ 'GET' ])
def index():
	return render_template("index.html", agenda=dataAgenda)

@agenda.route('/create', methods = [ 'GET', 'POST' ])
def create():
	form = CreateForm()
	if form.validate_on_submit():
		id = form.id.data
		content = form.content.data

		dataAgenda.append({ 'id': id, 'content': content })

		return redirect(url_for('agenda.index'))
	return render_template("create.html", form=form)

templates/create.html
{% extends "layout.html" %}

{% block title %} Agenda {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <h3>Create</h3>

    <form method="POST">
        {{ form.csrf_token }}
        {{ form.id.label }}
        {{ form.id() }}
        {{ form.content.label }}
        {{ form.content() }}
        <button>Create</button>
    </form>

    <a href="{{ url_for('agenda.index') }}">Back</a>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %} Agenda {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <h1>Agenda</h1>

    <div>
        {% for item in agenda %}
            <div>
                <div> {{ item.id }} - {{ item.content }} </div>
            </div>
        {% endfor %}
    </div>

    <a href="{{ url_for('agenda.create') }}">Create</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block head %}
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>{% block title %} {% endblock %}</title>

		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='style.css') }}"
		/>
		{% endblock %}
	</head>
	<body>
		<div id="content">
            {% block content %} {% endblock %}
        </div>
	</body>
</html>